In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.2


In [3]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
z=np.zeros(10*10)
print('%d bytes' % (z.size*z.itemsize))

800 bytes


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [13]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [15]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
z = np.random.random((3,3,3))
print(z)

[[[3.14544330e-02 1.70590744e-01 2.63513560e-01]
  [8.76082404e-01 4.37607384e-01 1.91333201e-01]
  [8.18176478e-01 3.56466844e-04 7.13147374e-01]]

 [[3.19393018e-01 4.16554478e-01 6.12229253e-01]
  [8.44751220e-01 9.33193315e-01 7.90687182e-01]
  [9.31090063e-01 8.20681459e-02 9.61561672e-01]]

 [[9.63993492e-01 9.29265935e-01 5.20326854e-01]
  [5.24370035e-01 9.03908707e-02 4.12234704e-01]
  [6.59097283e-01 6.74629912e-01 3.64938846e-01]]]


In [22]:
z = np.random.random((10,10))
zmin , zmax = z.min(),z.max()
print(zmin,zmax)

0.013183639222998034 0.9988717032800523


In [24]:
z = np.random.random(30)
m = z.mean()
print(m)

0.6013618447675547


In [25]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [26]:
z = np.ones((5,5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [27]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [31]:
z = np.diag(np.arange(1,5), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [39]:
z = np.zeros((8,8),dtype = int)
z[::2,::2] = 1
z[1::2,1::2] = 1
print(z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [40]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [41]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
z = np.random.random((5,5))
zmin,zmax = z.min(),z.max()
z = (z - zmin)/(zmax - zmin)
print(z)

[[0.0977786  0.43130661 0.188116   0.29289501 0.00258073]
 [0.84963561 0.78633363 1.         0.         0.33431139]
 [0.74529125 0.94127649 0.82802516 0.75301408 0.09126754]
 [0.72309643 0.54696759 0.01382313 0.13644299 0.58215069]
 [0.17312584 0.28623628 0.44275868 0.1101407  0.1977336 ]]


In [46]:
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [47]:
z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [49]:
z = np.arange(10)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [50]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [57]:
z = np.arange(5)
z ** z

array([  1,   1,   4,  27, 256], dtype=int32)

In [58]:
z = np.arange(5)
2 << z >> 2

array([0, 1, 2, 4, 8], dtype=int32)

In [59]:
z = np.arange(5)
z <- z

array([False, False, False, False, False])

In [61]:
z = np.arange(5)
1j * z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [62]:
z = np.arange(5)
z/1/1

array([0., 1., 2., 3., 4.])

In [63]:
z = np.arange(5)
z < z > z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [64]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [66]:
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[ -9.  10.   6. -10.   8.   1.  -4.   6.  -4.   1.]


In [68]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(np,intersect1d(z1,z2))

<module 'numpy' from 'E:\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'> [0 2 3 4 7]


In [79]:
# Suicide mode on
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [80]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [81]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-07
Today is 2019-08-08
Tomorrow is 2019-08-09


In [82]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [85]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [87]:
z = np.random.uniform(0,10,10)
print (z - z%1)
print (np.floor(z))
print (np.ceil(z)-1)
print (z.astype(int))
print (np.trunc(z))

[0. 5. 5. 5. 4. 1. 8. 1. 8. 1.]
[0. 5. 5. 5. 4. 1. 8. 1. 8. 1.]
[0. 5. 5. 5. 4. 1. 8. 1. 8. 1.]
[0 5 5 5 4 1 8 1 8 1]
[0. 5. 5. 5. 4. 1. 8. 1. 8. 1.]


In [88]:
z= np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [89]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print (z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [90]:
z = np.linspace(0,1,11,endpoint=False)[1:]
print (z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [91]:
z = np.random.random(10)
z.sort()
print (z)

[0.00288724 0.15331563 0.16565091 0.18514123 0.31152597 0.40316184
 0.43038288 0.67610681 0.8776423  0.96072241]


In [92]:
z = np.arange(10)
np.add.reduce(z)

45

In [93]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [94]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [95]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
R = np.sqrt(x**2+y**2)
T = np.arctan2(y,x)
print (R)
print (T)

[0.66748076 0.82455874 1.10118353 0.83907436 0.50483318 1.31700676
 0.93216033 1.03406601 0.50191545 1.03517508]
[1.0592677  0.94860849 0.8567704  1.26451091 0.55265621 0.82587448
 0.2487412  0.92765138 0.40935922 0.46495326]


In [ ]:
z = np.random.random(10)
z[z.argmax()] = 1
print (z)

In [98]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [129]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666


In [100]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [131]:
np.set_printoptions(threshold = 256)
z = np.zeros((16,16))
print (z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [104]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print (z[index])

52
